services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: vet_frontend_app
    ports:
      - "3000:80"
    networks:
      - vet-network
    restart: always

networks:
  vet-network:
    name: vet-network
    driver: bridge